version: '3.8'

services:
    api:
        image: ${DOCKER_REGISTRY-}upnodoapi
        build:
            context: .
            dockerfile: src/Upnodo.Api/Dockerfile

    mongo:
        image: mongo
        container_name: "upnodo-db"